spring:
  profiles:
    active: local
    group:
      local: local, common, secret

---

spring:
  config:
    activate:
      on-profile: local

server:
  prot: 8080
  name: local

---

spring:
  config:
    activate:
      on-profile: common

mybatis:
  mapper-locations:
    - /mappers/*.xml
