spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.cfyce4k2m3rb.ap-northeast-2.rds.amazonaws.com:3306/library_db
    username: aws
    password: 1q2w3e4r!!

jwt:
  secret: NjsgPIc/Y8WCnyvHrmkFZ1v8z0Pv1dkn7w6lEjIbXX/BIlgZ7g+vZx4hqPOBS8rU